---
- name: Copy slaves into place
  template: 
    src: slaves.js2 
    dest: "{{ hadoop_rootfolder}}/hadoop/etc/hadoop/slaves"
    owner: "{{ hadoop_user }}" 
    group: "{{ hadoop_group}}"
  tags:
    - copyslaves
    - prepnamenode
    - hadoop

# Create hdfs RSA ssh keys for passwordless ssh from nn to dn
- name: create hdfs ssh keys
  user: 
    name: "{{ hadoop_user }}"
    state: present
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    force: yes
  tags:
  - prereqs
  - sshkeys
  - hadoop

- name: get the public key back to the controller
  fetch: 
    src="/home/{{ hadoop_user }}/.ssh/id_rsa.pub"
    dest="{{ tmp_folder }}/root.id_rsa.pub"
    mode=444
    flat=yes
  tags:
    - prereqs
    - sshkeys
    - hadoop


- name: distribute the public key for loopback connection
  authorized_key:
    user: "{{ hadoop_user }}" 
    key: "{{ lookup('file', '{{ tmp_folder }}/root.id_rsa.pub') }}"
  tags:
    - prereqs
    - sshkeys
    - hadoop